# Generated by Django 6.0.5 on 2026-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets",
         "0002_asset_archived_at_asset_condition_asset_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="acknowledgment_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetallocationhistory",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetallocationhistory",
            name="acknowledgment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("acknowledged", "Acknowledged"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending_acknowledgment", "Pending Acknowledgment"),
                    ("assigned", "Assigned"),
                    ("under_repair", "Under Repair"),
                    ("retired", "Retired"),
                ],
                default="available",
                max_length=25,
            ),
        ),
    ]
