# Generated by Django 6.0.5 on 2026-07-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_asset_acknowledged_at_and_more"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="master_data.assetcategory",
            ),
        ),
    ]
