# Generated by Django 6.0.5 on 2026-07-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_category"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="master_data.assetcategory",
            ),
        ),
    ]
