# Generated by Django 6.0.5 on 2026-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_remove_asset_asset_type_alter_asset_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending_acknowledgment", "Pending Acknowledgment"),
                    ("assigned", "Assigned"),
                    ("pending_return", "Pending Return"),
                    ("under_repair", "Under Repair"),
                    ("retired", "Retired"),
                ],
                default="available",
                max_length=25,
            ),
        ),
    ]
