# Generated by Django 6.0.5 on 2026-08-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_alter_asset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetallocationhistory",
            name="asset_id_snapshot",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="assetallocationhistory",
            name="asset_name_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="assetallocationhistory",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocation_history",
                to="assets.asset",
            ),
        ),
    ]
