# Generated by Django 6.0.5 on 2026-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_backfill_allocation_snapshots"),
        ("employees", "0005_employee_employee_archived_status_idx"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_archived", "status"], name="asset_archived_status_idx"
            ),
        ),
    ]
