# Generated by Django 6.0.5 on 2026-08-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_asset_asset_archived_status_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["id"]},
        ),
    ]
