# Generated by Django 6.0.5 on 2026-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_alter_asset_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending_acknowledgment", "Pending Acknowledgment"),
                    ("assigned", "Assigned"),
                    ("pending_return", "Pending Return"),
                    ("under_repair", "Under Repair"),
                    ("lost", "Lost"),
                    ("retired", "Retired"),
                    ("reserved", "Reserved"),
                ],
                default="available",
                max_length=25,
            ),
        ),
    ]
