# Generated by Django 6.0.5 on 2026-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_alter_asset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="asset",
            name="qr_generated_at",
            field=models.DateTimeField(
                blank=True,
                null=True),
        ),
    ]
