# Generated by Django 6.0.5 on 2026-08-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_qr_code_image_asset_qr_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocationhistory',
            name='transfer_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('reallocation',
                     'Reallocation'),
                    ('damage',
                     'Damage / Replacement'),
                    ('upgrade',
                     'Upgrade'),
                    ('role_change',
                     'Role Change'),
                    ('other',
                     'Other')],
                max_length=20),
        ),
    ]
