# Generated by Django 6.0.5 on 2026-09-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_assetallocationhistory_transfer_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetallocationhistory",
            name="condition_at_issue",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("damaged", "Damaged"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetallocationhistory",
            name="expected_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
