# Generated by Django 6.0.5 on 2026-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcategory",
            name="asset_id_prefix",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                unique=True),
        ),
    ]
