# Generated by Django 6.0.5 on 2026-05-31 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_rename_status_employee_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('resignation', 'Resignation'), (
                    'termination', 'Termination'), ('contract_end', 'Contract End'), ('retirement', 'Retirement')], max_length=20)),
                ('exit_interview_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), (
                    'completed', 'Completed'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('asset_recovery_status', models.BooleanField(default=False)),
                ('access_revocation_status', models.BooleanField(default=False)),
                ('manager_clearance_status', models.BooleanField(default=False)),
                ('hr_clearance_status', models.BooleanField(default=False)),
                ('final_clearance_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='offboarding_checklist', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OffboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_to_role', models.CharField(choices=[
                 ('hr', 'HR'), ('it', 'IT Admin'), ('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                 ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='completed_offboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='offboarding_tasks', to='employees.employee')),
            ],
        ),
    ]
