# Generated by Django 6.0.5 on 2026-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingchecklist',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingchecklist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offboardingtask',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offboardingtask',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
