# Generated by Django 6.0.5 on 2026-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0002_offboardingchecklist_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingchecklist",
            name="offboarding_completion_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
