# Generated by Django 6.0.5 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_onboardingchecklist_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingtask",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
