# Generated by Django 6.0.5 on 2026-05-31 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_rename_status_employee_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('offer_letter', 'Offer Letter'), ('nda', 'NDA'), ('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('passport', 'Passport'), (
                    'educational_certificate', 'Educational Certificate'), ('experience_certificate', 'Experience Certificate'), ('policy_acceptance', 'Policy Acceptance Form'), ('exit_document', 'Exit Document'), ('other', 'Other')], max_length=30)),
                ('document_file', models.FileField(
                    blank=True, null=True, upload_to='documents/')),
                ('verification_status', models.CharField(choices=[
                 ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='documents', to='employees.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
