# Generated by Django 6.0.5 on 2026-08-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_archived_at_document_is_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
    ]
