# Generated by Django 6.0.5 on 2026-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_archived_at_employee_archived_by_and_more"), ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("joining_pending", "Joining Pending"),
                    ("active", "Active"),
                    ("notice_period", "Notice Period"),
                    ("offboarding", "Offboarding"),
                    ("exited", "Exited"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
