# Generated by Django 6.0.5 on 2026-08-01 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_current_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_archived", "current_status"],
                name="employee_archived_status_idx",
            ),
        ),
    ]
