# Generated by Django 6.0.5 on 2026-08-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_employee_archived_status_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveIndex(
            model_name="employee",
            name="employee_archived_status_idx",
        ),
    ]
