# Generated by Django 6.0.5 on 2026-08-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_employee_archived_status_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="alternate_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be 10 to 15 digits only",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate"),
                    ("offer_sent", "Offer Sent"),
                    ("joining_pending", "Joining Pending"),
                    ("onboarding", "Onboarding"),
                    ("active", "Active"),
                    ("notice_period", "Notice Period"),
                    ("offboarding", "Offboarding"),
                    ("exited", "Exited"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be 10 to 15 digits only",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be 10 to 15 digits only",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
