# Generated by Django 6.0.5 on 2026-08-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_make_candidate_fields_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
    ]
