# Generated by Django 6.0.5 on 2026-08-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditlog_auditlog_model_object_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_model_object_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="auditlog_created_at_idx",
        ),
    ]
